# Урок 2

##  Тема: Вычисления с помощью Numpy

##### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. 
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 
Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [2]:
lst = [[1,2,3,3,1],
       [6,8,11,10,7]]
a = np.array(lst).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
# Рабочий, но не идеальный вариант
mean_a = np.array([0,0], dtype=np.float64)
for n in range(a.shape[1]):
    mean_a[n] = a.T[n].mean()
mean_a

array([2. , 8.4])

In [4]:
# Вариант универсальнее, ЧЕРЕЗ append
mean_a = np.array([])
for n in range(a.shape[1]):
    new_data = np.array([a.T[n].mean()])
    mean_a = np.append(mean_a, new_data, axis=0)
mean_a

array([2. , 8.4])