In [2]:
import numpy as np

In [4]:
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

a = np.arange(12, 24)

In [ ]:
print(a)


[12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [ ]:
a.shape, a.ndim, a.size

((12,), 1, 12)

In [ ]:
print(np.reshape(a, (2, 6)))
print(np.reshape(a, (3, 4)))
print(np.reshape(a, (4, 3)))
print(np.reshape(a, (6, 2)))
print(np.reshape(a, (12, 1)))
#a

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [5]:
# Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

print(np.reshape(a, (2, -1)))
print(np.reshape(a, (3, -1)))
print(np.reshape(a, (4, -1)))
print(np.reshape(a, (-1, 2)))
print(np.reshape(a, (-1, 1)))

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [17]:
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
a0 = np.ones((12))
a1 = np.ones((12, 1))
a2 = np.ones((1, 12))
print (a0, a1, a2, sep='\n'*2)
print (a0.ndim, a1.ndim, a2.ndim)
# Ответ: Нет, массив, состоящий из одного столбца и 12 строк (a1) является двумерным. Более того, массив из 1 строки и 12 столбцов (a2) также является двумерным. 
# Одномерным является массив (a0) с 12 элементами, но у одномерного массива отсутствуют понятия строки и столбцы (это уже 2 измерения), 
# но присутствуют только элементы, обладающие порядковым номером (1 измерение).

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1 2 2


In [24]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения 
# со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
# Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

rnd = np.random.randn(3, 4)
# rnd
rnd.flatten()

array([ 0.0918485 , -0.34396677, -0.30268004, -2.11219877,  0.85459312,
        0.11515289,  2.30733828, -0.50975517, -1.03290916, -0.03793719,
       -1.12488352, -0.17549727])

In [28]:
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [30]:
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a и b?
b = np.reshape(a, (1, -1))
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [32]:
print(a.ndim, b.ndim)
# массив а - одномерный, массив b - двумерный

1 2


In [42]:
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2,2))
b = np.ones((3,2))
ab = np.vstack((a, b))
print(ab)
print(ab.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [61]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
# Получить матрицу At путем транспонирования матрицы A. 
# Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? 
# Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(12)
A = a.reshape((4, 3))
At = A.T
B = np.dot(A, At)
print(B)
print('shape(B) = ', B.shape)
# print(np.linalg.inv(B))  # LinAlgError: Singular matrix
print('det(B) = ', np.linalg.det(B))  # т.к. определитель равен 0

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
shape(B) =  (4, 4)
det(B) =  0.0


In [63]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)
# далее - проверка:
rnd1 = np.random.randint(0, 10**6, 5)
np.random.seed(42)
rnd2 = np.random.randint(0, 10**6, 5)
print(rnd1, rnd2, sep='\n')

[121958 671155 131932 365838 259178]
[121958 671155 131932 365838 259178]


In [66]:
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([ 8,  0, 10, 10, 14,  9, 15, 11, 11, 15, 14, 13, 13, 14, 13,  2])

In [72]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C. 
# Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
# Вычислите определитель, ранг и обратную матрицу D_inv для D.
C = c.reshape((4,4))
print(C)
D = B + C * 10
print(D)

[[ 8  0 10 10]
 [14  9 15 11]
 [11 15 14 13]
 [13 14 13  2]]
[[ 85  14 123 132]
 [154 140 236 232]
 [133 236 289 342]
 [162 262 342 322]]


In [73]:
np.linalg.det(D)

-57153999.99999996

In [75]:
np.linalg.matrix_rank(D)

4

In [76]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.01792001,  0.03497218, -0.00075235, -0.01705217],
       [-0.01788396,  0.0115607 ,  0.00252196, -0.00367673],
       [ 0.01961158, -0.02498303, -0.01450957,  0.02537145],
       [ 0.00273752, -0.00046646,  0.01373727, -0.01227106]])

In [79]:
test = np.dot(D,D_inv)
np.around(test, 3)

array([[ 1., -0., -0.,  0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

In [83]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
# Убедитесь, что в матрице D_inv остались только нули и единицы. 
# С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
# а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  
# Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
# должны быть равны соответствующему элементу матрицы B, 
# а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, 
# должны быть равны соответствующему элементу матрицы C.

D_inv

array([[-0.01792001,  0.03497218, -0.00075235, -0.01705217],
       [-0.01788396,  0.0115607 ,  0.00252196, -0.00367673],
       [ 0.01961158, -0.02498303, -0.01450957,  0.02537145],
       [ 0.00273752, -0.00046646,  0.01373727, -0.01227106]])

In [85]:
D_inv[D_inv < 0] = 0
D_inv

array([[0.        , 0.03497218, 0.        , 0.        ],
       [0.        , 0.0115607 , 0.00252196, 0.        ],
       [0.01961158, 0.        , 0.        , 0.02537145],
       [0.00273752, 0.        , 0.01373727, 0.        ]])

In [86]:
D_inv[D_inv > 0] = 1
D_inv

array([[0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [90]:
print(B, C, sep='\n')
E = np.where(D_inv, B, C)
print(E)
# Проверка:
# print(E - B)
# print(E - C)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 8  0 10 10]
 [14  9 15 11]
 [11 15 14 13]
 [13 14 13  2]]
[[  8  14  10  10]
 [ 14  50  86  11]
 [ 23  15  14 212]
 [ 32  14 212   2]]
[[   3    0  -13  -22]
 [   0    0    0 -111]
 [   0  -71 -135    0]
 [   0 -108    0 -300]]
[[  0  14   0   0]
 [  0  41  71   0]
 [ 12   0   0 199]
 [ 19   0 199   0]]
